namespace Manabind.Src.UI.Enums
{
    public enum EventType
    {
        Initialise,
        LeftClick,
        RightClick,
        Hover,
        HoverLeave,
        LeftMouseDown,
        LeftMouseUp,
        RightMouseDown,
        RightMouseUp,
        Select,
        Deselect,
        ChangeWidth,
        ChangeHeight,
        ChangeText,
        KeyPress,
        ScrollLoadFiles,
        MapSaved,
        MapLoaded,
        RefreshTree,
        UnitHover,
        UnitSelected,
        UnitDeselected,
        AbilitySelected,
        TemplateSelected,
        ChangeTools,
        Update
    }
}
